[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Docs"
authors = [{name = "VMescheryakov", email = "vm@del-fin"}]
dynamic = ["version", "description"]
